import type { Metadata } from "next";
import "./global.css";
import Header from "./components/header";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="xl:ml-[5%] xl:mr-[5%]">
                <Header logo_path="/hamster_nord_borderless.svg" />
                {children}
            </body>
        </html>
    );
}
